module.exports = {
  planners: [
    { tag: 'daily planner 2026', subNiche: 'Daily Planning' },
    { tag: 'daily schedule', subNiche: 'Daily Planning' },
    { tag: 'daily organizer', subNiche: 'Daily Planning' },
    { tag: 'hourly planner', subNiche: 'Daily Planning' },
    { tag: 'daily to do list', subNiche: 'Daily Planning' },
    { tag: 'day planner', subNiche: 'Daily Planning' },
    { tag: 'daily agenda', subNiche: 'Daily Planning' },
    { tag: 'time block planner', subNiche: 'Daily Planning' },
    { tag: 'daily routine', subNiche: 'Daily Planning' },
    { tag: 'today planner page', subNiche: 'Daily Planning' },
    { tag: 'weekly planner 2026', subNiche: 'Weekly Planning' },
    { tag: 'weekly schedule', subNiche: 'Weekly Planning' },
    { tag: 'weekly organizer', subNiche: 'Weekly Planning' },
    { tag: 'week on two pages', subNiche: 'Weekly Planning' },
    { tag: 'weekly spread', subNiche: 'Weekly Planning' },
    { tag: 'weekly layout', subNiche: 'Weekly Planning' },
    { tag: 'weekly overview', subNiche: 'Weekly Planning' },
    { tag: 'weekly to do list', subNiche: 'Weekly Planning' },
    { tag: 'weekly goals', subNiche: 'Weekly Planning' },
    { tag: 'week at a glance', subNiche: 'Weekly Planning' },
    { tag: 'monthly planner', subNiche: 'Monthly Planning' },
    { tag: 'monthly calendar', subNiche: 'Monthly Planning' },
    { tag: 'monthly overview', subNiche: 'Monthly Planning' },
    { tag: 'monthly schedule', subNiche: 'Monthly Planning' },
    { tag: 'monthly organizer', subNiche: 'Monthly Planning' },
    { tag: 'month at a glance', subNiche: 'Monthly Planning' },
    { tag: 'calendar 2026', subNiche: 'Monthly Planning' },
    { tag: 'monthly goals', subNiche: 'Monthly Planning' },
    { tag: 'monthly tracker', subNiche: 'Monthly Planning' },
    { tag: 'yearly overview', subNiche: 'Monthly Planning' },
    { tag: 'meal planner', subNiche: 'Specialty Planners' },
    { tag: 'fitness planner', subNiche: 'Specialty Planners' },
    { tag: 'wedding planner', subNiche: 'Specialty Planners' },
    { tag: 'budget planner', subNiche: 'Specialty Planners' },
    { tag: 'goal planner', subNiche: 'Specialty Planners' },
    { tag: 'habit tracker', subNiche: 'Specialty Planners' },
    { tag: 'pregnancy planner', subNiche: 'Specialty Planners' },
    { tag: 'travel planner', subNiche: 'Specialty Planners' },
    { tag: 'ADHD planner', subNiche: 'Specialty Planners' },
    { tag: 'self care planner', subNiche: 'Specialty Planners' },
    { tag: 'student planner', subNiche: 'Academic' },
    { tag: 'teacher planner', subNiche: 'Academic' },
    { tag: 'academic planner', subNiche: 'Academic' },
    { tag: 'college planner', subNiche: 'Academic' },
    { tag: 'school planner', subNiche: 'Academic' },
    { tag: 'study planner', subNiche: 'Academic' },
    { tag: 'assignment tracker', subNiche: 'Academic' },
    { tag: 'exam planner', subNiche: 'Academic' },
    { tag: 'grade tracker', subNiche: 'Academic' },
    { tag: 'lesson planner', subNiche: 'Academic' },
    { tag: 'GoodNotes planner', subNiche: 'Digital Planning' },
    { tag: 'iPad planner', subNiche: 'Digital Planning' },
    { tag: 'digital planner', subNiche: 'Digital Planning' },
    { tag: 'Notability planner', subNiche: 'Digital Planning' },
    { tag: 'hyperlinked planner', subNiche: 'Digital Planning' },
    { tag: 'tablet planner', subNiche: 'Digital Planning' },
    { tag: 'digital stickers', subNiche: 'Digital Planning' },
    { tag: 'digital notebook', subNiche: 'Digital Planning' },
    { tag: 'clickable planner', subNiche: 'Digital Planning' },
    { tag: 'digital download', subNiche: 'Digital Planning' },
    { tag: 'gratitude journal', subNiche: 'Journals' },
    { tag: 'reading journal', subNiche: 'Journals' },
    { tag: 'travel journal', subNiche: 'Journals' },
    { tag: 'pregnancy journal', subNiche: 'Journals' },
    { tag: 'journal prompts', subNiche: 'Journals' },
    { tag: 'daily journal', subNiche: 'Journals' },
    { tag: 'reflection journal', subNiche: 'Journals' },
    { tag: 'mindfulness', subNiche: 'Journals' },
    { tag: 'wellness journal', subNiche: 'Journals' },
    { tag: 'mood tracker', subNiche: 'Journals' },
    { tag: 'printable planner', subNiche: 'Format & Style' },
    { tag: 'PDF planner', subNiche: 'Format & Style' },
    { tag: 'instant download', subNiche: 'Format & Style' },
    { tag: 'minimalist planner', subNiche: 'Format & Style' },
    { tag: 'undated planner', subNiche: 'Format & Style' },
    { tag: 'planner printable', subNiche: 'Format & Style' },
    { tag: 'A4 planner', subNiche: 'Format & Style' },
    { tag: 'US letter planner', subNiche: 'Format & Style' },
    { tag: 'black and white', subNiche: 'Format & Style' },
    { tag: 'boho planner', subNiche: 'Format & Style' },
    { tag: 'productivity', subNiche: 'Wellness & Goals' },
    { tag: 'goal setting', subNiche: 'Wellness & Goals' },
    { tag: 'brain dump', subNiche: 'Wellness & Goals' },
    { tag: 'time management', subNiche: 'Wellness & Goals' },
    { tag: 'priority planner', subNiche: 'Wellness & Goals' },
    { tag: 'focus planner', subNiche: 'Wellness & Goals' },
    { tag: 'vision board', subNiche: 'Wellness & Goals' },
    { tag: 'life planner', subNiche: 'Wellness & Goals' },
    { tag: 'new year planner', subNiche: 'Wellness & Goals' },
    { tag: 'self improvement', subNiche: 'Wellness & Goals' },
    { tag: 'planner insert', subNiche: 'Accessories' },
    { tag: 'planner refill', subNiche: 'Accessories' },
    { tag: 'planner binder', subNiche: 'Accessories' },
    { tag: 'happy planner', subNiche: 'Accessories' },
    { tag: 'A5 planner insert', subNiche: 'Accessories' },
    { tag: 'planner stickers', subNiche: 'Accessories' },
    { tag: 'planner dashboard', subNiche: 'Accessories' },
    { tag: 'planner divider', subNiche: 'Accessories' },
    { tag: 'planner cover', subNiche: 'Accessories' },
    { tag: 'planner bundle', subNiche: 'Accessories' },
  ],

  clipart: [
    { tag: 'watercolor flowers', subNiche: 'Floral' },
    { tag: 'floral clipart', subNiche: 'Floral' },
    { tag: 'rose clipart', subNiche: 'Floral' },
    { tag: 'peony clipart', subNiche: 'Floral' },
    { tag: 'flower PNG', subNiche: 'Floral' },
    { tag: 'wildflower clipart', subNiche: 'Floral' },
    { tag: 'daisy clipart', subNiche: 'Floral' },
    { tag: 'sunflower clipart', subNiche: 'Floral' },
    { tag: 'floral wreath', subNiche: 'Floral' },
    { tag: 'flower bouquet PNG', subNiche: 'Floral' },
    { tag: 'botanical clipart', subNiche: 'Floral' },
    { tag: 'floral border', subNiche: 'Floral' },
    { tag: 'greenery clipart', subNiche: 'Floral' },
    { tag: 'woodland animals', subNiche: 'Animals' },
    { tag: 'fox clipart', subNiche: 'Animals' },
    { tag: 'deer clipart', subNiche: 'Animals' },
    { tag: 'bear clipart', subNiche: 'Animals' },
    { tag: 'owl clipart', subNiche: 'Animals' },
    { tag: 'bunny clipart', subNiche: 'Animals' },
    { tag: 'butterfly clipart', subNiche: 'Animals' },
    { tag: 'bird clipart', subNiche: 'Animals' },
    { tag: 'animal clipart', subNiche: 'Animals' },
    { tag: 'safari animals', subNiche: 'Animals' },
    { tag: 'farm animals', subNiche: 'Animals' },
    { tag: 'Christmas clipart', subNiche: 'Holidays' },
    { tag: 'Halloween clipart', subNiche: 'Holidays' },
    { tag: 'Easter clipart', subNiche: 'Holidays' },
    { tag: 'Valentine clipart', subNiche: 'Holidays' },
    { tag: 'holiday graphics', subNiche: 'Holidays' },
    { tag: 'Santa clipart', subNiche: 'Holidays' },
    { tag: 'pumpkin clipart', subNiche: 'Holidays' },
    { tag: 'snowflake PNG', subNiche: 'Holidays' },
    { tag: 'ornament clipart', subNiche: 'Holidays' },
    { tag: 'festive clipart', subNiche: 'Holidays' },
    { tag: 'trick or treat', subNiche: 'Holidays' },
    { tag: 'Easter eggs PNG', subNiche: 'Holidays' },
    { tag: 'wedding clipart', subNiche: 'Events' },
    { tag: 'birthday clipart', subNiche: 'Events' },
    { tag: 'baby shower', subNiche: 'Events' },
    { tag: 'party clipart', subNiche: 'Events' },
    { tag: 'balloon clipart', subNiche: 'Events' },
    { tag: 'confetti PNG', subNiche: 'Events' },
    { tag: 'cake clipart', subNiche: 'Events' },
    { tag: 'celebration', subNiche: 'Events' },
    { tag: 'graduation clipart', subNiche: 'Events' },
    { tag: 'bridal shower', subNiche: 'Events' },
    { tag: 'back to school', subNiche: 'Events' },
    { tag: 'tropical clipart', subNiche: 'Nature & Seasons' },
    { tag: 'spring flowers', subNiche: 'Nature & Seasons' },
    { tag: 'autumn leaves', subNiche: 'Nature & Seasons' },
    { tag: 'ocean clipart', subNiche: 'Nature & Seasons' },
    { tag: 'beach clipart', subNiche: 'Nature & Seasons' },
    { tag: 'palm leaves', subNiche: 'Nature & Seasons' },
    { tag: 'mushroom clipart', subNiche: 'Nature & Seasons' },
    { tag: 'seashell clipart', subNiche: 'Nature & Seasons' },
    { tag: 'mountain clipart', subNiche: 'Nature & Seasons' },
    { tag: 'forest clipart', subNiche: 'Nature & Seasons' },
    { tag: 'cherry blossom', subNiche: 'Nature & Seasons' },
    { tag: 'winter clipart', subNiche: 'Nature & Seasons' },
    { tag: 'hand drawn frames', subNiche: 'Decorative' },
    { tag: 'vintage frames', subNiche: 'Decorative' },
    { tag: 'border clipart', subNiche: 'Decorative' },
    { tag: 'divider clipart', subNiche: 'Decorative' },
    { tag: 'wreath PNG', subNiche: 'Decorative' },
    { tag: 'corner clipart', subNiche: 'Decorative' },
    { tag: 'ribbon banner', subNiche: 'Decorative' },
    { tag: 'label clipart', subNiche: 'Decorative' },
    { tag: 'frame PNG', subNiche: 'Decorative' },
    { tag: 'flourish clipart', subNiche: 'Decorative' },
    { tag: 'food clipart', subNiche: 'Food & Kitchen' },
    { tag: 'fruit clipart', subNiche: 'Food & Kitchen' },
    { tag: 'baking clipart', subNiche: 'Food & Kitchen' },
    { tag: 'coffee clipart', subNiche: 'Food & Kitchen' },
    { tag: 'kitchen clipart', subNiche: 'Food & Kitchen' },
    { tag: 'cooking clipart', subNiche: 'Food & Kitchen' },
    { tag: 'vegetable clipart', subNiche: 'Food & Kitchen' },
    { tag: 'cupcake clipart', subNiche: 'Food & Kitchen' },
    { tag: 'boho clipart', subNiche: 'Style & Aesthetic' },
    { tag: 'celestial clipart', subNiche: 'Style & Aesthetic' },
    { tag: 'cottagecore', subNiche: 'Style & Aesthetic' },
    { tag: 'moon clipart', subNiche: 'Style & Aesthetic' },
    { tag: 'zodiac clipart', subNiche: 'Style & Aesthetic' },
    { tag: 'retro clipart', subNiche: 'Style & Aesthetic' },
    { tag: 'minimalist clipart', subNiche: 'Style & Aesthetic' },
    { tag: 'line art clipart', subNiche: 'Style & Aesthetic' },
    { tag: 'abstract shapes', subNiche: 'Style & Aesthetic' },
    { tag: 'dreamcatcher PNG', subNiche: 'Style & Aesthetic' },
    { tag: 'commercial use', subNiche: 'Usage & Format' },
    { tag: 'PNG clipart', subNiche: 'Usage & Format' },
    { tag: 'SVG clipart', subNiche: 'Usage & Format' },
    { tag: 'instant download', subNiche: 'Usage & Format' },
    { tag: 'digital download', subNiche: 'Usage & Format' },
    { tag: 'clipart bundle', subNiche: 'Usage & Format' },
    { tag: 'transparent PNG', subNiche: 'Usage & Format' },
    { tag: 'high resolution', subNiche: 'Usage & Format' },
    { tag: '300 DPI clipart', subNiche: 'Usage & Format' },
    { tag: 'scrapbook clipart', subNiche: 'Usage & Format' },
    { tag: 'planner stickers', subNiche: 'Usage & Format' },
    { tag: 'nursery clipart', subNiche: 'Usage & Format' },
    { tag: 'kids clipart', subNiche: 'Usage & Format' },
  ],

  wallArt: [
    { tag: 'line art print', subNiche: 'Minimalist' },
    { tag: 'minimalist art', subNiche: 'Minimalist' },
    { tag: 'single line art', subNiche: 'Minimalist' },
    { tag: 'abstract line art', subNiche: 'Minimalist' },
    { tag: 'modern wall art', subNiche: 'Minimalist' },
    { tag: 'simple wall art', subNiche: 'Minimalist' },
    { tag: 'minimal print', subNiche: 'Minimalist' },
    { tag: 'clean wall art', subNiche: 'Minimalist' },
    { tag: 'Scandinavian art', subNiche: 'Minimalist' },
    { tag: 'contemporary art', subNiche: 'Minimalist' },
    { tag: 'black and white art', subNiche: 'Minimalist' },
    { tag: 'neutral wall art', subNiche: 'Minimalist' },
    { tag: 'botanical print', subNiche: 'Botanical' },
    { tag: 'plant wall art', subNiche: 'Botanical' },
    { tag: 'eucalyptus print', subNiche: 'Botanical' },
    { tag: 'fern print', subNiche: 'Botanical' },
    { tag: 'monstera print', subNiche: 'Botanical' },
    { tag: 'leaf wall art', subNiche: 'Botanical' },
    { tag: 'green wall art', subNiche: 'Botanical' },
    { tag: 'nature print', subNiche: 'Botanical' },
    { tag: 'floral wall art', subNiche: 'Botanical' },
    { tag: 'watercolor floral', subNiche: 'Botanical' },
    { tag: 'flower print', subNiche: 'Botanical' },
    { tag: 'garden print', subNiche: 'Botanical' },
    { tag: 'nursery wall art', subNiche: 'Nursery' },
    { tag: 'baby room art', subNiche: 'Nursery' },
    { tag: 'kids room art', subNiche: 'Nursery' },
    { tag: 'nursery prints', subNiche: 'Nursery' },
    { tag: 'safari nursery', subNiche: 'Nursery' },
    { tag: 'animal prints', subNiche: 'Nursery' },
    { tag: 'playroom art', subNiche: 'Nursery' },
    { tag: 'gender neutral art', subNiche: 'Nursery' },
    { tag: 'toddler room art', subNiche: 'Nursery' },
    { tag: 'baby shower gift', subNiche: 'Nursery' },
    { tag: 'quote print', subNiche: 'Typography' },
    { tag: 'typography art', subNiche: 'Typography' },
    { tag: 'motivational print', subNiche: 'Typography' },
    { tag: 'inspirational art', subNiche: 'Typography' },
    { tag: 'affirmation print', subNiche: 'Typography' },
    { tag: 'word art print', subNiche: 'Typography' },
    { tag: 'be kind print', subNiche: 'Typography' },
    { tag: 'script font art', subNiche: 'Typography' },
    { tag: 'positive quotes', subNiche: 'Typography' },
    { tag: 'you are enough', subNiche: 'Typography' },
    { tag: 'abstract art print', subNiche: 'Abstract' },
    { tag: 'geometric print', subNiche: 'Abstract' },
    { tag: 'earth tone art', subNiche: 'Abstract' },
    { tag: 'mid century art', subNiche: 'Abstract' },
    { tag: 'terracotta art', subNiche: 'Abstract' },
    { tag: 'abstract shapes', subNiche: 'Abstract' },
    { tag: 'modern abstract', subNiche: 'Abstract' },
    { tag: 'color block art', subNiche: 'Abstract' },
    { tag: 'pastel abstract', subNiche: 'Abstract' },
    { tag: 'organic shapes', subNiche: 'Abstract' },
    { tag: 'landscape print', subNiche: 'Photography' },
    { tag: 'mountain print', subNiche: 'Photography' },
    { tag: 'forest print', subNiche: 'Photography' },
    { tag: 'ocean print', subNiche: 'Photography' },
    { tag: 'coastal print', subNiche: 'Photography' },
    { tag: 'beach print', subNiche: 'Photography' },
    { tag: 'fog forest', subNiche: 'Photography' },
    { tag: 'moody landscape', subNiche: 'Photography' },
    { tag: 'photography print', subNiche: 'Photography' },
    { tag: 'nature wall art', subNiche: 'Photography' },
    { tag: 'seasonal prints', subNiche: 'Seasonal' },
    { tag: 'spring wall art', subNiche: 'Seasonal' },
    { tag: 'summer print', subNiche: 'Seasonal' },
    { tag: 'fall wall art', subNiche: 'Seasonal' },
    { tag: 'winter print', subNiche: 'Seasonal' },
    { tag: 'Christmas print', subNiche: 'Seasonal' },
    { tag: 'autumn decor', subNiche: 'Seasonal' },
    { tag: 'holiday print', subNiche: 'Seasonal' },
    { tag: 'boho wall art', subNiche: 'Boho & Style' },
    { tag: 'boho print set', subNiche: 'Boho & Style' },
    { tag: 'desert print', subNiche: 'Boho & Style' },
    { tag: 'rainbow arch art', subNiche: 'Boho & Style' },
    { tag: 'sun print', subNiche: 'Boho & Style' },
    { tag: 'celestial art', subNiche: 'Boho & Style' },
    { tag: 'moon phases print', subNiche: 'Boho & Style' },
    { tag: 'space print', subNiche: 'Boho & Style' },
    { tag: 'vintage poster', subNiche: 'Boho & Style' },
    { tag: 'retro print', subNiche: 'Boho & Style' },
    { tag: 'gallery wall set', subNiche: 'Rooms & Format' },
    { tag: 'printable wall art', subNiche: 'Rooms & Format' },
    { tag: 'digital download', subNiche: 'Rooms & Format' },
    { tag: 'instant download', subNiche: 'Rooms & Format' },
    { tag: 'bedroom wall art', subNiche: 'Rooms & Format' },
    { tag: 'living room art', subNiche: 'Rooms & Format' },
    { tag: 'bathroom wall art', subNiche: 'Rooms & Format' },
    { tag: 'kitchen wall art', subNiche: 'Rooms & Format' },
    { tag: 'office wall art', subNiche: 'Rooms & Format' },
    { tag: 'home decor', subNiche: 'Rooms & Format' },
    { tag: 'wall decor print', subNiche: 'Rooms & Format' },
    { tag: 'printable art', subNiche: 'Rooms & Format' },
    { tag: 'set of 4 prints', subNiche: 'Rooms & Format' },
    { tag: 'set of 3 prints', subNiche: 'Rooms & Format' },
    { tag: 'large wall art', subNiche: 'Rooms & Format' },
    { tag: 'dorm room art', subNiche: 'Rooms & Format' },
    { tag: 'housewarming gift', subNiche: 'Rooms & Format' },
    { tag: 'pet portrait art', subNiche: 'Specialty' },
    { tag: 'music wall art', subNiche: 'Specialty' },
    { tag: 'travel poster', subNiche: 'Specialty' },
  ],

  socialMedia: [
    { tag: 'Instagram template', subNiche: 'Instagram' },
    { tag: 'Instagram post', subNiche: 'Instagram' },
    { tag: 'Instagram stories', subNiche: 'Instagram' },
    { tag: 'Instagram Reels', subNiche: 'Instagram' },
    { tag: 'IG template', subNiche: 'Instagram' },
    { tag: 'IG stories', subNiche: 'Instagram' },
    { tag: 'Reel covers', subNiche: 'Instagram' },
    { tag: 'carousel template', subNiche: 'Instagram' },
    { tag: 'feed template', subNiche: 'Instagram' },
    { tag: 'cohesive feed', subNiche: 'Instagram' },
    { tag: 'Instagram grid', subNiche: 'Instagram' },
    { tag: 'story template', subNiche: 'Instagram' },
    { tag: 'highlight covers', subNiche: 'Instagram' },
    { tag: 'Pinterest template', subNiche: 'Pinterest' },
    { tag: 'Pinterest pin', subNiche: 'Pinterest' },
    { tag: 'pin template', subNiche: 'Pinterest' },
    { tag: 'pin graphic', subNiche: 'Pinterest' },
    { tag: 'Pinterest graphic', subNiche: 'Pinterest' },
    { tag: 'blog pin', subNiche: 'Pinterest' },
    { tag: 'pin design', subNiche: 'Pinterest' },
    { tag: 'idea pin', subNiche: 'Pinterest' },
    { tag: 'Facebook cover', subNiche: 'Facebook' },
    { tag: 'Facebook banner', subNiche: 'Facebook' },
    { tag: 'Facebook post', subNiche: 'Facebook' },
    { tag: 'FB template', subNiche: 'Facebook' },
    { tag: 'Facebook group', subNiche: 'Facebook' },
    { tag: 'cover photo', subNiche: 'Facebook' },
    { tag: 'FB cover photo', subNiche: 'Facebook' },
    { tag: 'YouTube thumbnail', subNiche: 'YouTube' },
    { tag: 'video thumbnail', subNiche: 'YouTube' },
    { tag: 'YouTube banner', subNiche: 'YouTube' },
    { tag: 'YT thumbnail', subNiche: 'YouTube' },
    { tag: 'YouTube template', subNiche: 'YouTube' },
    { tag: 'channel art', subNiche: 'YouTube' },
    { tag: 'end screen', subNiche: 'YouTube' },
    { tag: 'TikTok template', subNiche: 'TikTok' },
    { tag: 'TikTok cover', subNiche: 'TikTok' },
    { tag: 'video cover', subNiche: 'TikTok' },
    { tag: 'TikTok branding', subNiche: 'TikTok' },
    { tag: 'short form video', subNiche: 'TikTok' },
    { tag: 'LinkedIn template', subNiche: 'Multi-Platform' },
    { tag: 'LinkedIn post', subNiche: 'Multi-Platform' },
    { tag: 'podcast template', subNiche: 'Multi-Platform' },
    { tag: 'podcast art', subNiche: 'Multi-Platform' },
    { tag: 'email header', subNiche: 'Multi-Platform' },
    { tag: 'social media kit', subNiche: 'Multi-Platform' },
    { tag: 'social media bundle', subNiche: 'Multi-Platform' },
    { tag: 'multi platform', subNiche: 'Multi-Platform' },
    { tag: 'cross platform', subNiche: 'Multi-Platform' },
    { tag: 'Canva template', subNiche: 'Design & Tools' },
    { tag: 'Canva editable', subNiche: 'Design & Tools' },
    { tag: 'drag and drop', subNiche: 'Design & Tools' },
    { tag: 'brand template', subNiche: 'Design & Tools' },
    { tag: 'brand kit', subNiche: 'Design & Tools' },
    { tag: 'branding template', subNiche: 'Design & Tools' },
    { tag: 'style guide', subNiche: 'Design & Tools' },
    { tag: 'brand board', subNiche: 'Design & Tools' },
    { tag: 'color palette', subNiche: 'Design & Tools' },
    { tag: 'font pairing', subNiche: 'Design & Tools' },
    { tag: 'logo template', subNiche: 'Design & Tools' },
    { tag: 'real estate', subNiche: 'Industry' },
    { tag: 'realtor template', subNiche: 'Industry' },
    { tag: 'restaurant', subNiche: 'Industry' },
    { tag: 'fitness template', subNiche: 'Industry' },
    { tag: 'yoga template', subNiche: 'Industry' },
    { tag: 'coaching template', subNiche: 'Industry' },
    { tag: 'salon template', subNiche: 'Industry' },
    { tag: 'wedding vendor', subNiche: 'Industry' },
    { tag: 'bakery template', subNiche: 'Industry' },
    { tag: 'course creator', subNiche: 'Industry' },
    { tag: 'launch template', subNiche: 'Promotional' },
    { tag: 'sale template', subNiche: 'Promotional' },
    { tag: 'promo graphic', subNiche: 'Promotional' },
    { tag: 'Black Friday', subNiche: 'Promotional' },
    { tag: 'holiday sale', subNiche: 'Promotional' },
    { tag: 'flash sale', subNiche: 'Promotional' },
    { tag: 'testimonial post', subNiche: 'Promotional' },
    { tag: 'review template', subNiche: 'Promotional' },
    { tag: 'social proof', subNiche: 'Promotional' },
    { tag: 'countdown post', subNiche: 'Promotional' },
    { tag: 'small business', subNiche: 'Audience' },
    { tag: 'content creator', subNiche: 'Audience' },
    { tag: 'digital marketing', subNiche: 'Audience' },
    { tag: 'marketing template', subNiche: 'Audience' },
    { tag: 'entrepreneur', subNiche: 'Audience' },
    { tag: 'online business', subNiche: 'Audience' },
    { tag: 'influencer', subNiche: 'Audience' },
    { tag: 'blogger template', subNiche: 'Audience' },
    { tag: 'Etsy seller', subNiche: 'Audience' },
    { tag: 'instant download', subNiche: 'Format' },
    { tag: 'digital download', subNiche: 'Format' },
    { tag: 'editable template', subNiche: 'Format' },
    { tag: 'quote template', subNiche: 'Content Type' },
    { tag: 'quote post', subNiche: 'Content Type' },
    { tag: 'tip post', subNiche: 'Content Type' },
    { tag: 'engagement post', subNiche: 'Content Type' },
    { tag: 'educational post', subNiche: 'Content Type' },
    { tag: 'motivational post', subNiche: 'Content Type' },
    { tag: 'audiogram', subNiche: 'Content Type' },
    { tag: 'infographic', subNiche: 'Content Type' },
    { tag: 'announcement post', subNiche: 'Content Type' },
    { tag: 'behind the scenes', subNiche: 'Content Type' },
  ],

  budget: [
    { tag: 'monthly budget', subNiche: 'Budgeting' },
    { tag: 'budget spreadsheet', subNiche: 'Budgeting' },
    { tag: 'budget template', subNiche: 'Budgeting' },
    { tag: 'budget planner', subNiche: 'Budgeting' },
    { tag: 'annual budget', subNiche: 'Budgeting' },
    { tag: 'weekly budget', subNiche: 'Budgeting' },
    { tag: 'biweekly budget', subNiche: 'Budgeting' },
    { tag: 'paycheck budget', subNiche: 'Budgeting' },
    { tag: 'zero based budget', subNiche: 'Budgeting' },
    { tag: 'envelope budget', subNiche: 'Budgeting' },
    { tag: 'cash envelope', subNiche: 'Budgeting' },
    { tag: 'family budget', subNiche: 'Budgeting' },
    { tag: 'simple budget', subNiche: 'Budgeting' },
    { tag: 'beginner budget', subNiche: 'Budgeting' },
    { tag: 'debt payoff', subNiche: 'Debt' },
    { tag: 'debt tracker', subNiche: 'Debt' },
    { tag: 'debt snowball', subNiche: 'Debt' },
    { tag: 'debt avalanche', subNiche: 'Debt' },
    { tag: 'debt free', subNiche: 'Debt' },
    { tag: 'debt free journey', subNiche: 'Debt' },
    { tag: 'loan tracker', subNiche: 'Debt' },
    { tag: 'credit card payoff', subNiche: 'Debt' },
    { tag: 'student loan', subNiche: 'Debt' },
    { tag: 'payoff calculator', subNiche: 'Debt' },
    { tag: 'savings tracker', subNiche: 'Savings' },
    { tag: 'savings challenge', subNiche: 'Savings' },
    { tag: '52 week challenge', subNiche: 'Savings' },
    { tag: 'emergency fund', subNiche: 'Savings' },
    { tag: 'sinking funds', subNiche: 'Savings' },
    { tag: 'savings goal', subNiche: 'Savings' },
    { tag: 'save money', subNiche: 'Savings' },
    { tag: 'no spend challenge', subNiche: 'Savings' },
    { tag: 'money challenge', subNiche: 'Savings' },
    { tag: 'rainy day fund', subNiche: 'Savings' },
    { tag: 'vacation fund', subNiche: 'Savings' },
    { tag: 'Christmas savings', subNiche: 'Savings' },
    { tag: 'expense tracker', subNiche: 'Tracking' },
    { tag: 'spending tracker', subNiche: 'Tracking' },
    { tag: 'bill tracker', subNiche: 'Tracking' },
    { tag: 'income tracker', subNiche: 'Tracking' },
    { tag: 'cash flow tracker', subNiche: 'Tracking' },
    { tag: 'net worth tracker', subNiche: 'Tracking' },
    { tag: 'payment tracker', subNiche: 'Tracking' },
    { tag: 'subscription audit', subNiche: 'Tracking' },
    { tag: 'money tracker', subNiche: 'Tracking' },
    { tag: 'daily expenses', subNiche: 'Tracking' },
    { tag: 'spending log', subNiche: 'Tracking' },
    { tag: 'receipt tracker', subNiche: 'Tracking' },
    { tag: 'small business', subNiche: 'Business' },
    { tag: 'business budget', subNiche: 'Business' },
    { tag: 'profit tracker', subNiche: 'Business' },
    { tag: 'revenue tracker', subNiche: 'Business' },
    { tag: 'freelancer', subNiche: 'Business' },
    { tag: 'side hustle', subNiche: 'Business' },
    { tag: 'Etsy seller', subNiche: 'Business' },
    { tag: 'tax tracker', subNiche: 'Business' },
    { tag: 'invoice tracker', subNiche: 'Business' },
    { tag: 'mileage tracker', subNiche: 'Business' },
    { tag: 'business finance', subNiche: 'Business' },
    { tag: 'gig economy', subNiche: 'Business' },
    { tag: 'investment tracker', subNiche: 'Investment' },
    { tag: 'stock tracker', subNiche: 'Investment' },
    { tag: 'crypto tracker', subNiche: 'Investment' },
    { tag: 'portfolio tracker', subNiche: 'Investment' },
    { tag: 'dividend tracker', subNiche: 'Investment' },
    { tag: 'asset tracker', subNiche: 'Investment' },
    { tag: 'wealth tracker', subNiche: 'Investment' },
    { tag: 'retirement plan', subNiche: 'Investment' },
    { tag: 'financial goals', subNiche: 'Planning' },
    { tag: 'SMART goals', subNiche: 'Planning' },
    { tag: 'money goals', subNiche: 'Planning' },
    { tag: 'financial planner', subNiche: 'Planning' },
    { tag: 'money planner', subNiche: 'Planning' },
    { tag: 'financial plan', subNiche: 'Planning' },
    { tag: 'money management', subNiche: 'Planning' },
    { tag: 'personal finance', subNiche: 'Planning' },
    { tag: 'finance template', subNiche: 'Planning' },
    { tag: 'wedding budget', subNiche: 'Specialty Budgets' },
    { tag: 'college budget', subNiche: 'Specialty Budgets' },
    { tag: 'baby budget', subNiche: 'Specialty Budgets' },
    { tag: 'moving budget', subNiche: 'Specialty Budgets' },
    { tag: 'home buying', subNiche: 'Specialty Budgets' },
    { tag: 'renovation budget', subNiche: 'Specialty Budgets' },
    { tag: 'travel budget', subNiche: 'Specialty Budgets' },
    { tag: 'holiday budget', subNiche: 'Specialty Budgets' },
    { tag: 'Google Sheets', subNiche: 'Format' },
    { tag: 'Excel template', subNiche: 'Format' },
    { tag: 'spreadsheet', subNiche: 'Format' },
    { tag: 'instant download', subNiche: 'Format' },
    { tag: 'digital download', subNiche: 'Format' },
    { tag: 'printable tracker', subNiche: 'Format' },
    { tag: 'auto calculate', subNiche: 'Format' },
    { tag: 'pre built formulas', subNiche: 'Format' },
    { tag: 'editable template', subNiche: 'Format' },
    { tag: 'frugal living', subNiche: 'Lifestyle' },
    { tag: 'minimalist budget', subNiche: 'Lifestyle' },
    { tag: 'debt free living', subNiche: 'Lifestyle' },
    { tag: 'financial freedom', subNiche: 'Lifestyle' },
    { tag: 'money mindset', subNiche: 'Lifestyle' },
    { tag: 'adulting', subNiche: 'Lifestyle' },
  ],
};
